### ISSUE TITLE
proper installation guide is required 

### ISSUE THREAD

**Issue by subha7595** [BubbleGumOP/LoanCraft#1]

**Comment by subha7595** [comment]
it will be better for beginers to understand and how to run and all

**Comment by HariHaranRN** [comment]
First you must installed the node ,npm and angular CLI.
Clone this repository to your local system.
now open the both folder separately on your IDE also in terminal.
run 'npm install' on both terminal.
To run this project type 'ng-serve' on your frontend terminal and 'node app.js' on your backend terminal.
Now open browser and enter "http://localhost:4200/".
